dist: trusty

language: go

go:
  - "1.10"
  - "1.11"

go_import_path: github.com/pepabo/go-netapp
env:
  - GO111MODULE=auto

# Only build pull requests, pushes to the master branch, and branches
# starting with `test-`. This is a convenient way to push branches to
# your own fork of the repostiory to ensure Travis passes before submitting
# a PR. For instance, you might run:
# git push myremote branchname:test-branchname
branches:
  only:
    - master
    - /^test-.*$/

script: go test ./netapp
